2025-09-28 19:25:00,844 -INFO - the value of x is 2 - root - MainThread
2025-09-28 19:27:14,542 -ERROR - ZeroDivisionError - root - MainThread
Traceback (most recent call last):
  File "/tmp/ipykernel_13609/3589094887.py", line 3, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2025-09-28 19:30:36,347 -ERROR - ZeroDivisionError - root - MainThread
Traceback (most recent call last):
  File "/tmp/ipykernel_13609/4056771532.py", line 3, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2025-09-28 19:30:36,347 -ERROR - ZeroDivisionError - root - MainThread
Traceback (most recent call last):
  File "/tmp/ipykernel_13609/4056771532.py", line 3, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2025-09-28 19:34:19,253 -INFO - this is info from custom logger - __main__ - MainThread
2025-09-28 19:37:05,133 -INFO - this is info from custom logger - __main__ - MainThread
2025-09-28 19:38:16,628 -INFO - this is info from custom logger - __main__ - MainThread
